FROM osrf/ros:SRC-TAG
ARG ros_distro

# convenience utils
# upgrade everything that is not updated in base docker image
RUN apt update && apt upgrade -y && apt install -y \
	xterm \
	zsh \
	gdb \
	strace \
	openssh-client \
	vim \
	less \
	tmux \
	ycmd \
	python3-pip

# need to install this way because it is not released for debian
RUN pip3 install catkin_lint

# block zsh new user startup
RUN rm /usr/share/zsh/*/scripts/newuser

# additional ros packages
RUN apt install -y \
	ros-${ros_distro}-tf2-bullet \
	ros-${ros_distro}-tf2-eigen \
	ros-${ros_distro}-robot-localization \
	ros-${ros_distro}-move-base \
	ros-${ros_distro}-perception \
	ros-${ros_distro}-opencv3 \
	ros-${ros_distro}-map-server \
	ros-${ros_distro}-rtabmap-ros \
	pcl-tools \
	python-bloom

# currently broken pluginlib: ros-${ros_distro}-gmapping

# cleanup
RUN rm -rf /var/lib/apt/lists/*

ADD zshrc.local /etc/zsh/zshrc.local
ADD zshrc /etc/zsh/zshrc

ENTRYPOINT ["zsh"]
